# Generated by Django 2.1.5 on 2019-04-11 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='HahuImg')),
            ],
        ),
        migrations.CreateModel(
            name='Hahuautok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kep', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Hahudeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=100)),
                ('marka', models.CharField(max_length=100)),
                ('kategoria', models.CharField(max_length=100)),
                ('modell', models.CharField(max_length=100)),
                ('tipus', models.CharField(max_length=100)),
                ('uzemanyag', models.CharField(max_length=15, null=True)),
                ('futottkm', models.CharField(max_length=10)),
                ('evjarat', models.CharField(max_length=10)),
                ('sebessegvalto', models.CharField(max_length=30, null=True)),
                ('hengerurtartalom', models.CharField(max_length=30, null=True)),
                ('felszereltseg', models.CharField(max_length=500, null=True)),
                ('teljesitmeny', models.CharField(max_length=30, null=True)),
                ('hengerelrendezes', models.CharField(max_length=30, null=True)),
                ('telefonszam', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cachedimage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='finalbp.Hahudeta'),
        ),
    ]
