# Generated by Django 2.1.5 on 2019-03-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
    ]
