# Generated by Django 2.1.5 on 2019-03-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
    ]
