# Generated by Django 2.1.5 on 2019-04-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hahudeta',
            name='muszaki',
        ),
    ]
