# Generated by Django 2.1.5 on 2019-04-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hahudeta',
            name='evjarat',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hahudeta',
            name='felszereltseg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hahudeta',
            name='futottkm',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hahudeta',
            name='hengerelrendezes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hahudeta',
            name='hengerurtartalom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hahudeta',
            name='kategoria',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hahudeta',
            name='marka',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hahudeta',
            name='modell',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hahudeta',
            name='rank',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hahudeta',
            name='sebessegvalto',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hahudeta',
            name='telefonszam',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hahudeta',
            name='teljesitmeny',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hahudeta',
            name='tipus',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hahudeta',
            name='uzemanyag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
