# Generated by Django 2.1.5 on 2019-04-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hahudeta',
            name='evjarat',
            field=models.CharField(max_length=10),
        ),
    ]
