# Generated by Django 2.1.5 on 2019-03-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0002_remove_car_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hahuautok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kep', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('rank', models.CharField(max_length=100)),
                ('marka', models.CharField(max_length=100)),
                ('kategoria', models.CharField(max_length=100)),
                ('modell', models.CharField(max_length=100)),
                ('tipus', models.CharField(max_length=100)),
            ],
        ),
    ]
