# Generated by Django 2.1.5 on 2019-04-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0002_auto_20190411_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hahudeta',
            name='felszereltseg',
            field=models.TextField(null=True),
        ),
    ]
