# Generated by Django 2.1.5 on 2019-03-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0003_hahuautok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hahuautok',
            name='kep',
            field=models.ImageField(blank=True, null=True, upload_to='static/Hahuimages'),
        ),
    ]
