# Generated by Django 2.1.5 on 2019-04-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0003_auto_20190411_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hahudeta',
            name='felszereltseg',
        ),
        migrations.RemoveField(
            model_name='hahudeta',
            name='hengerelrendezes',
        ),
        migrations.RemoveField(
            model_name='hahudeta',
            name='hengerurtartalom',
        ),
        migrations.RemoveField(
            model_name='hahudeta',
            name='sebessegvalto',
        ),
        migrations.RemoveField(
            model_name='hahudeta',
            name='teljesitmeny',
        ),
    ]
