# Generated by Django 2.1.5 on 2019-04-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0004_auto_20190412_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='hahudeta',
            name='ar',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
