# Generated by Django 2.1.5 on 2019-03-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0004_auto_20190318_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hahuautok',
            name='kep',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
