# Generated by Django 2.1.5 on 2019-04-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0006_auto_20190428_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='hahudeta',
            name='leiras',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
