# Generated by Django 2.1.5 on 2019-05-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0007_hahudeta_leiras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hahudeta',
            name='leiras',
            field=models.TextField(null=True),
        ),
    ]
