# Generated by Django 2.1.5 on 2019-05-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0008_auto_20190502_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=250, null=True)),


                ('draft', models.BooleanField(default=False)),
            ],
        ),
    ]
