# Generated by Django 2.1.5 on 2019-03-18 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0009_auto_20190318_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hahudeta',
            name='kep',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='finalbp.Hahuautok'),
        ),
    ]
