# Generated by Django 2.1.5 on 2019-05-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0009_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
