# Generated by Django 2.1.5 on 2019-05-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0010_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hahudeta',
            name='evjarat',
            field=models.DateField(),
        ),
    ]
