# Generated by Django 2.1.5 on 2019-03-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0010_auto_20190318_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hahudeta',
            name='kep',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
