# Generated by Django 2.1.5 on 2019-03-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0011_auto_20190318_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hahudeta',
            name='kep',
        ),
    ]
