# Generated by Django 2.1.5 on 2019-03-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0012_remove_hahudeta_kep'),
    ]

    operations = [
        migrations.AddField(
            model_name='hahudeta',
            name='kepdocument',
            field=models.ImageField(blank=True, null=True, upload_to='static/HahuImg/'),
        ),
    ]
