# Generated by Django 2.1.5 on 2019-03-24 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0013_hahudeta_kepdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hahudeta',
            name='kepdocument',
        ),
    ]
