# Generated by Django 2.1.5 on 2019-03-26 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalbp', '0014_remove_hahudeta_kepdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='HahuImg')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='finalbp.Hahudeta')),
            ],
        ),
    ]
