# Generated by Django 2.1.5 on 2019-04-04 10:04

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vezetéknév', models.CharField(max_length=50)),
                ('Email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('Telefonszám', phone_field.models.PhoneField(blank=True, help_text='Amin eltudjuk érni', max_length=31)),
                ('Üzenet', models.TextField()),
            ],
        ),
    ]
