# Generated by Django 2.1.5 on 2019-03-18 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190314_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='gepkocsimarkaja',
            new_name='Gépkocsimárkája',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='keresztnev',
            new_name='Keresztnév',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='Telefonszám',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='vezeteknev',
            new_name='Vezetéknév',
        ),
    ]
