# Generated by Django 2.1.5 on 2019-03-18 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190318_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='gepkocsirendszama',
            new_name='Gépkocsirendszáma',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='gepkocsitipus',
            new_name='Gépkocsitipusa',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='uzenet',
            new_name='Üzenet',
        ),
    ]
