# Generated by Django 2.1.5 on 2019-03-29 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190318_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Gépkocsimárkája',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Gépkocsirendszáma',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Gépkocsitipusa',
        ),
    ]
