# Generated by Django 2.1.5 on 2019-03-29 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190330_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Keresztnév',
        ),
    ]
