# Generated by Django 2.1.5 on 2019-05-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='texttwo',
            field=models.TextField(blank=True),
        ),
    ]
