# Generated by Django 2.1.5 on 2019-02-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpcore', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
