# Generated by Django 2.1.5 on 2019-03-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpcore', '0003_post_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
