# Generated by Django 2.1.5 on 2019-05-20 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpcore', '0003_post1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
